name: Build and deploy documentation on GitHub Pages

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Add zip file download links to the installation instructions
              run: |
                  LATEST_STABLE_VERSION=$(git tag --list 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1 | xargs git describe --tags --abbrev=0)
                  LATEST_PRERELEASE_VERSION=$(git tag --list 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+-(?:alpha|beta)\.[0-9]{10}$' | sort -V | tail -n 1 | xargs git describe --tags --abbrev=0)
                  echo "Latest stable version: $LATEST_STABLE_VERSION"
                  echo "Latest prerelease version: $LATEST_PRERELEASE_VERSION"
                  cat docs/install-and-update-instructions/script.js \
                    | sed s,LATEST_STABLE_VERSION,$LATEST_STABLE_VERSION, \
                    | sed s,LATEST_PRERELEASE_VERSION,$LATEST_PRERELEASE_VERSION, \
                    | tee docs/install-and-update-instructions/script.js >/dev/null
            - name: Set up GitHub Pages
              id: pages
              uses: actions/configure-pages@v5
            - name: Build with Jekyll
              uses: actions/jekyll-build-pages@v1
              with:
                  source: ./
                  destination: ./_site
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
    deploy:
        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
